matrix:
  include:
  - name: Android Build
    language: android
    jdk: oraclejdk8
    android:
      components:
        - build-tools-28.0.3
        - android-28
        - extra-android-m2repository
      licenses:
       - 'android-sdk-preview-license-52d11cd2'
       - 'android-sdk-license-.+'
       - 'google-gdk-license-.+'
    before_install:
     - touch $HOME/.android/repositories.cfg
     - yes | sdkmanager "platforms;android-28"
     - yes | sdkmanager "build-tools;28.0.3"
    before_script:
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    script:
      - flutter packages get
      - flutter build apk
  - name: iOS Build
    os: osx
    language: generic
    osx_image: xcode10.2
    before_script:
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    script:
      - flutter packages get
      - flutter build ios --no-codesign
